version: '3.8'

services:
  # PostgreSQL Database
  database:
    image: postgres:15
    container_name: erasmos-db
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
      - ./database/migrations:/docker-entrypoint-initdb.d/migrations
    networks:
      - erasmos-network

  # Backend API Server  
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: erasmos-backend
    env_file:
      - ./backend/.env
    environment:
      NODE_ENV: development
      DB_HOST: database
      DB_PORT: 5432
      DB_NAME: postgres
      DB_USER: postgres
      DB_PASSWORD: mysecretpassword
      JWT_SECRET: mySuperSecretKey123
      SENDGRID_API_KEY: ${SENDGRID_API_KEY:-your-sendgrid-api-key-here}
      EMAIL_FROM: ${EMAIL_FROM:-no-reply@erasmos.app}
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    depends_on:
      - database
    networks:
      - erasmos-network
    command: npm run dev

  # Frontend React Application
  frontend:
    build:
      context: ./frontend  
      dockerfile: Dockerfile
    container_name: erasmos-frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - erasmos-network
    command: npm run dev

volumes:
  postgres_data:

networks:
  erasmos-network:
    driver: bridge